---
# Serial port name
port: /dev/ttyUSB0
# Bolid printer port to ademco contact ID

# Object Number
acct: 4673

# Message type, contains = 18. 
# Used to indicate the Contact ID protocol.
mt: 18

# Event type

qualifiers:
  ПОЖАР           : 1
  ВНИМАНИЕ        : 1
  ТРЕВОГА         : 1
  ТИХАЯ ТРЕВОГА   : 1
  ТРЕВОГА ВХОДА   : 1
  ОБРЫВ ШС        : 1
  КОРОТКОЕ ЗАМЫКАН: 1
  НЕИСПРАВНОСТЬ   : 1
  ВОССТАНОВЛЕНИЕ  : 3
  ОШИБКА ПАРАМ.ШС : 1
  ОТКЛЮЧЕН ШС     : 1
  В0ССТ.30НЫ      : 3
  НЕВЗЯТИЕ        : 1
  СБРОС ТРЕВОГИ ШС: 3
  ВЗЯТ ШС         : 3
  СНЯТ ШС         : 1
  ВЗЛОМ КОРПУСА   : 1
  ВОССТ.КОРПУСА   : 3
  СРАБОТКА ДАТЧИКА: 1
  НЕОБХ.ОБСЛ      : 3
  ПОВЫШ.ТЕМПЕР.   : 1
  ПОНИЖ.ТЕМПЕР.   : 1
  НОРМА ТЕМПЕР.   : 3
  НЕИСП.ТЕРМОМЕТРА: 1
  АВАРИЯ ПИТАНИЯ  : 1
  ВОССТ.ПИТАНИЯ   : 3
  АВАРИЯ БАТАРЕИ  : 1
  ВОССТ.БАТАРЕИ   : 3
  АВАРИЯ 220В     : 1
  ВОССТ.220В      : 3
  СБРОС ПРИБОРА   : 3
  ПОТЕРЯН ПРИБОР  : 1
  ОБНАРУЖЕН ПРИБОР: 3
  ОТКЛ.ВЕТВИ RS485: 1
  ВСТ.ВЕТВИ RS485 : 3
  КЗ ДПЛС         : 1
  ВОССТАНОВЛ.ДПЛС : 3
  НАРУШ.ТЕХНОЛ.ШС : 1
  ВОССТ.ТЕХНОЛ.ШС : 3
  НЕНОРМАШС       : 1
  ВОССТАНОВЛ.ШС   : 3
  РАЗДЕЛ ВЗЯТ     : 3
  РАЗДЕЛ СНЯТ     : 1
  ЗАПРОС ВЗЯТИЯ   : 3
  ЗАПРОС СНЯТИЯ   : 1
  ИДЕНТИФИКАЦИЯ ХО: 1
  ОБРЫВ ВЫХОДА    : 1
  КЗ ВЫХОДА       : 1
  ОТКЛ.ВЫХОДА     : 1
  ВОССТ.ВЫХОДА    : 3
  УСПЕШНЫЙ ЗАПУСК : 3
  НЕУСП.ЗАПУСК    : 1
  АВТОМАТИКА ВЫКЛ.: 1
  АВТОМАТИКА ВКЛ. : 3
  ПУСКАСПТ        : 3
  ЗАДЕРЖКА ЗАПУСКА: 3
  БЛОКИР.ПУСКА    : 1
  АВАРИЙНЫЙ ПУСК  : 1
  СРАБАТЫВАНИЕ СДУ: 1
  ОТКАЗ СДУ       : 1
  ПРОХОД          : 1
  ДОСТУП ОТКЛОНЕН : 3
  ДОСТУП ПРЕДОСТАВ: 3
  ДОСТУП ЗАПРЕЩЕН : 1
  ДОСТУП ЗАКРЫТ   : 1
  ДОСТУП ОТКРЫТ   : 3
  ДОСТУП ВОССТАНОВ: 3
  ДВЕРЬ ЗАБЛОКИР. : 1
  ДВЕРЬ РАЗБЛОКИР.: 3
  ДВЕРЬ ВЗЛОМАНА  : 1
  ПРОГРАММИРОВАНИЕ: 1
  НЕИСПР.ТЕЛ.ЛИНИИ: 1
  ЖУРНАЛ ЗАПОЛНЕН : 1
  ЖУРНАЛ ПЕРЕПОЛН.: 1
  ЗАПУСК ТЕСТА    : 1
  РЕАКЦИЯ         : 1
  ВКЛЮЧЕНИЕ ПУЛЬТА: 1
  ВКЛ. ПРИНТЕРА   : 3
  ВЫКЛ. ПРИНТЕРА  : 1
  ИЗМ.ДАТЫ        : 1
  ИЗМ.ВРЕМЕНИ     : 1
  ДАТА            : 1
  ОТМЕТКА ВРЕМЕНИ : 1
  ПОДКЛЮЧЕН ВЫХОД : 3
  ОТКЛЮЧЕН ВЫХОД  : 1
  ОТКЛЮЧЕН        : 1
  ПОДКЛЮЧЕН       : 3
  ВКЛ.ТЕСТ ИЗВЕЩ. : 1
  ВЫКЛ.ТЕСТ ИЗВЕЩ.: 3
  ТЕСТ ИЗВЕЩАТЕЛЯ : 1
  НЕИСП.ТЕРМОМЕТРА: 1
  ВКЛ. НАСОСА     : 1
  ВЫКЛ. НАСОСА    : 3
  АКБ РАЗРЯЖЕНА   : 1
  ОШИБКА ТЕСТА АКБ: 1
  ПЕРЕГРУЗКА РИП  : 1
  УСТР. ПЕРЕГР.РИП: 3
  АВАРИЯ ДПЛС     : 1
  ОШИБКА В ОТВЕТЕ : 1
  НЕУСТ. СВЯЗЬ    : 1
  ВОССТ. ТЕЛ.ЛИНИИ: 3
  ОШИБКА ТЕСТА    : 1
  ПУСКАУП         : 3
  ТУШЕНИЕ         : 3
  НЕУДАЧНЫЙ ПУСК  : 1
  ОТМЕНА ПУСКА    : 1
  ЗАДЕРЖКА ВЗЯТИЯ : 3
  ВКЛ. КОНТРОЛЬ ШС: 3
  НАРУШ.ТЕХНОЛ.ШС : 1
  ПУСК РО         : 1
  ОТМЕНА ПУСКА РО : 3
  РАБОЧ.СОСТОЯНИЕ : 3
  ИСХОДН.СОСТОЯНИЕ: 3
  ОШИБ. УПРАВЛЕНИЯ: 1
  ОШИБ. УПРАВЛЕНИЯ: 1
  ОШИБКА КОНТРОЛЯ : 1
  ПОВЫШ. УРОВНЯ   : 1
  ПОНИЖ. УРОВНЯ   : 1
  НОРМА УРОВНЯ    : 3
  АВ.ПОВЫШ.УРОВНЯ : 1
  АВ.ПОНИЖ.У РОВНЯ: 1
  НЕИСПР. ЗУ РИП  : 1
  ВОССТ. ЗУ РИП   : 3
  ОТКЛЮЧЕН РИП    : 1
  ВКЛЮЧЕН РИП     : 3
  НЕТ СВЯЗИ ДПЛС1 : 1
  НЕТ СВЯЗИ ДПЛС2 : 1
  УСТ.СВЯЗЬ ДПЛС1 : 3
  УСТ.СВЯЗЬ ДПЛС2 : 3
  НЕИЗВ.УСТР0ЙСТВ0: 1
  ВОССТ. ВЫХОДА   : 3
  РЕЛЕ ВКЛЮЧЕНО   : 1
  РЕЛЕ ВКЛ.ПРЕРЫВ.: 1
  ОТМЕТКА НАРЯДА  : 3

# Three-digit event code
ademco-code:
  ПОЖАР           : 0x110
  ВНИМАНИЕ        : 0x118
  ТРЕВОГА         : 0x130
  ТИХАЯ ТРЕВОГА   : 0x122
  ТРЕВОГА ВХОДА   : 0x134
  ОБРЫВ ШС        : 0x371
  КОРОТКОЕ ЗАМЫКАН: 0x372
  НЕИСПРАВНОСТЬ   : 0x380
  ВОССТАНОВЛЕНИЕ  : 0x380
  ОШИБКА ПАРАМ.ШС : 0x380
  ОТКЛЮЧЕН ШС     : 0x382
  В0ССТ.30НЫ      : 0x382
  НЕВЗЯТИЕ        : 0x374
  СБРОС ТРЕВОГИ ШС: 0x406
  ВЗЯТ ШС         : 0x400
  СНЯТ ШС         : 0x400
  ВЗЛОМ КОРПУСА   : 0x341
  ВОССТ.КОРПУСА   : 0x341
  СРАБОТКА ДАТЧИКА: 0x118
  НЕОБХ.ОБСЛ      : 0x393
  ПОВЫШ.ТЕМПЕР.   : 0x158
  ПОНИЖ.ТЕМПЕР.   : 0x159
  НОРМА ТЕМПЕР.   : 0x158
  НЕИСП.ТЕРМОМЕТРА: 0x380
  АВАРИЯ ПИТАНИЯ  : 0x337
  ВОССТ.ПИТАНИЯ   : 0x337
  АВАРИЯ БАТАРЕИ  : 0x338
  ВОССТ.БАТАРЕИ   : 0x338
  АВАРИЯ 220В     : 0x301
  ВОССТ.220В      : 0x301
  СБРОС ПРИБОРА   : 0x339
  ПОТЕРЯН ПРИБОР  : 0x333
  ОБНАРУЖЕН ПРИБОР: 0x333
  ОТКЛ.ВЕТВИ RS485: 0x331
  ВСТ.ВЕТВИ RS485 : 0x331
  КЗ ДПЛС         : 0x332
  ВОССТАНОВЛ.ДПЛС : 0x332
  НАРУШ.ТЕХНОЛ.ШС : 0x150
  ВОССТ.ТЕХНОЛ.ШС : 0x150
  НЕНОРМАШС       : 0x331
  ВОССТАНОВЛ.ШС   : 0x331
  РАЗДЕЛ ВЗЯТ     : 0x402
  РАЗДЕЛ СНЯТ     : 0x402
  ЗАПРОС ВЗЯТИЯ   : 0x462
  ЗАПРОС СНЯТИЯ   : 0x462
  ИДЕНТИФИКАЦИЯ ХО: 0x401
  ОБРЫВ ВЫХОДА    : 0x320
  КЗ ВЫХОДА       : 0x320
  ОТКЛ.ВЫХОДА     : 0x382
  ВОССТ.ВЫХОДА    : 0x382
  УСПЕШНЫЙ ЗАПУСК : 0x560
  НЕУСП.ЗАПУСК    : 0x560
  АВТОМАТИКА ВЫКЛ.: 0x561
  АВТОМАТИКА ВКЛ. : 0x561
  ПУСКАСПТ        : 0x119
  ЗАДЕРЖКА ЗАПУСКА: 0x119
  БЛОКИР.ПУСКА    : 0x119
  АВАРИЙНЫЙ ПУСК  : 0x119
  СРАБАТЫВАНИЕ СДУ: 0x308
  ОТКАЗ СДУ       : 0x308
  ПРОХОД          : 0x458
  ДОСТУП ОТКЛОНЕН : 0x461
  ДОСТУП ПРЕДОСТАВ: 0x421
  ДОСТУП ЗАПРЕЩЕН : 0x421
  ДОСТУП ЗАКРЫТ   : 0x421
  ДОСТУП ОТКРЫТ   : 0x421
  ДОСТУП ВОССТАНОВ: 0x421
  ДВЕРЬ ЗАБЛОКИР. : 0x426
  ДВЕРЬ РАЗБЛОКИР.: 0x426
  ДВЕРЬ ВЗЛОМАНА  : 0x426
  ПРОГРАММИРОВАНИЕ: 0x627
  НЕИСПР.ТЕЛ.ЛИНИИ: 0x351
  ЖУРНАЛ ЗАПОЛНЕН : 0x623
  ЖУРНАЛ ПЕРЕПОЛН.: 0x624
  ЗАПУСК ТЕСТА    : 0x601
  РЕАКЦИЯ         : 0x406
  ВКЛЮЧЕНИЕ ПУЛЬТА: 0x305
  ВКЛ. ПРИНТЕРА   : 0x336
  ВЫКЛ. ПРИНТЕРА  : 0x336
  ИЗМ.ДАТЫ        : 0x625
  ИЗМ.ВРЕМЕНИ     : 0x625
  ДАТА            : 0x625
  ОТМЕТКА ВРЕМЕНИ : 0x625
  ПОДКЛЮЧЕН ВЫХОД : 0x382
  ОТКЛЮЧЕН ВЫХОД  : 0x382
  ОТКЛЮЧЕН        : 0x382
  ПОДКЛЮЧЕН       : 0x382
  ВКЛ.ТЕСТ ИЗВЕЩ. : 0x607
  ВЫКЛ.ТЕСТ ИЗВЕЩ.: 0x607
  ТЕСТ ИЗВЕЩАТЕЛЯ : 0x611
  НЕИСП.ТЕРМОМЕТРА: 0x380
  ВКЛ. НАСОСА     : 0x205
  ВЫКЛ. НАСОСА    : 0x205
  АКБ РАЗРЯЖЕНА   : 0x302
  ОШИБКА ТЕСТА АКБ: 0x309
  ПЕРЕГРУЗКА РИП  : 0x312
  УСТР. ПЕРЕГР.РИП: 0x312
  АВАРИЯ ДПЛС     : 0x332
  ОШИБКА В ОТВЕТЕ : 0x382
  НЕУСТ. СВЯЗЬ    : 0x382
  ВОССТ. ТЕЛ.ЛИНИИ: 0x351
  ОШИБКА ТЕСТА    : 0x343
  ПУСКАУП         : 0x119
  ТУШЕНИЕ         : 0x113
  НЕУДАЧНЫЙ ПУСК  : 0x560
  ОТМЕНА ПУСКА    : 0x560
  ЗАДЕРЖКА ВЗЯТИЯ : 0x404
  ВКЛ. КОНТРОЛЬ ШС: 0x341
  НАРУШ.ТЕХНОЛ.ШС : 0x341
  ПУСК РО         : 0x606
  ОТМЕНА ПУСКА РО : 0x606
  РАБОЧ.СОСТОЯНИЕ : 0x203
  ИСХОДН.СОСТОЯНИЕ: 0x203
  ОШИБ. УПРАВЛЕНИЯ: 0x203
  ОШИБ. УПРАВЛЕНИЯ: 0x203
  ОШИБКА КОНТРОЛЯ : 0x203
  ПОВЫШ. УРОВНЯ   : 0x204
  ПОНИЖ. УРОВНЯ   : 0x204
  НОРМА УРОВНЯ    : 0x204
  АВ.ПОВЫШ.УРОВНЯ : 0x204
  АВ.ПОНИЖ.У РОВНЯ: 0x204
  НЕИСПР. ЗУ РИП  : 0x309
  ВОССТ. ЗУ РИП   : 0x309
  ОТКЛЮЧЕН РИП    : 0x309
  ВКЛЮЧЕН РИП     : 0x309
  НЕТ СВЯЗИ ДПЛС1 : 0x382
  НЕТ СВЯЗИ ДПЛС2 : 0x382
  УСТ.СВЯЗЬ ДПЛС1 : 0x382
  УСТ.СВЯЗЬ ДПЛС2 : 0x382
  НЕИЗВ.УСТР0ЙСТВ0: 0x605
  ВОССТ. ВЫХОДА   : 0x382
  РЕЛЕ ВКЛЮЧЕНО   : 0x382
  РЕЛЕ ВКЛ.ПРЕРЫВ.: 0x382
  ОТМЕТКА НАРЯДА  : 0x250
