---
# Serial port name
port: /dev/ttyUSB0

# Bolid printer port to ademco contact ID
# Event type ver.4.12

qualifiers: 
   ["ЗАДЕРЖКА ПУСКА  ",   
    "ОСТАНОВ ЗАДЕРЖКИ",
    "СБРОС ЗАДЕРЖКИ  ",
    "ПУСК            ",
    "ПУСК РО         ",
    "ТУШЕНИЕ         ",
    "АВАРИЙНЫЙ ПУСК  ",
    "НЕУДАЧНЫЙ ПУСК  ",
    "ОТКАЗ           ",
    "БЛОКИР. ПУСКА   ",
    "ОТМЕНА ПУСКА    ",
    "ОСТАНОВ         ",
    "ОСТАНОВ РО      ",
    "РАБОЧ.СОСТОЯНИЕ ",
    "ИСХОДН.СОСТОЯНИЕ",
    "ОТКАЗ ИСП.У-ВА  ",
    "ОШИБКА ИСП.У-ВА ",
    "ВКЛ. НАСОСА     ",
    "ВЫКЛ. НАСОСА    ",
    "ПОЖАР2          ",
    "ПОЖАР           ",
    "ВНИМАНИЕ        ",
    "ТРЕВОГА         ",
    "ТИХАЯ ТРЕВОГА   ",
    "ПРИНУЖДЕНИЕ     ",
    "СНЯТ принуждение",
    "ТРЕВОГА ВХОДА   ",
    "ЗАТОПЛЕНИЕ      ",
    "ВОССТАНОВЛ. ДЗ  ",
    "ОБРЫВ ШС        ",
    "КОРОТКОЕ ЗАМЫКАН",
    "ОБРЫВ ВЫХОДА    ",
    "КЗ ВЫХОДА       ",
    "ВОССТ. ВЫХОДА   ",
    "НЕИСПРАВНОСТЬ   ",
    "ВОССТАНОВЛЕНИЕ  ",
    "ПОМЕХА          ",
    "ПОМЕХА УСТРАНЕНА",
    "ОШИБКА ПАРАМ.ШС ",
    "ПОТЕРЯ СВЯЗИ    ",
    "ВОССТАНОВЛ.СВЯЗИ",
    "НЕОБХ.ОБСЛ      ",
    "ВОССТАНОВЛЕНИЕ  ",
    "НЕВЗЯТИЕ        ",
    "СБРОС ТРЕВОГИ ШС",
    "АВТОМАТИКА ВЫКЛ.",
    "АВТОМАТИКА ВКЛ. ",
    "ОТКЛЮЧЕН        ",
    "ВКЛЮЧЕН         ",
    "ВЫХ.ОТКЛЮЧ.     ",
    "ВЫХ.ВКЛЮЧЕН     ",
    "ВКЛ.КОНТРОЛЬ ШС ",
    "ВЗЯТ ШС         ",
    "СНЯТ ШС         ",
    "ЗАДЕРЖКА ВЗЯТИЯ ",
    "ВКЛ.ТЕСТ        ",
    "ВЫКЛ.ТЕСТ       ",
    "ТЕСТ ИЗВЕЩАТЕЛЯ ",
    "СРАБОТКА ДАТЧИКА",
    "НАРУШ.ТЕХНОЛ.ШС ",
    "ВОССТ.ТЕХНОЛ.ШС ",
    "НАРУШ.2 ТЕХН.ШС ",
    "АКТИВАЦИЯ УДП   ",
    "ВОССТАНОВЛ.УДП  ",
    "НЕНОРМА ШС      ",
    "ВОССТАНОВЛ.ШС   ",
    "ВЗЛОМ КОРПУСА   ",
    "ВОССТ.КОРПУСА   ",
    "ПОВЫШ.ТЕМПЕР.   ",
    "ПОНИЖ.ТЕМПЕР.   ",
    "НОРМА ТЕМПЕР.   ",
    "НЕИСП.ТЕРМОМЕТРА",
    "ВОССТ.ТЕРМОМЕТРА",
    "СРАБАТЫВАНИЕ СДУ",
    "ОТКАЗ СДУ       ",
    "ВКЛ.ИСП.УСТР-ВА ",
    "ВЫКЛ.ИСП.УСТР-ВА",
    "ПОВЫШ. УРОВНЯ   ",
    "ПОНИЖ. УРОВНЯ   ",
    "НОРМА УРОВНЯ    ",
    "АВ.ПОВЫШ.УРОВНЯ ",
    "АВ.ПОНИЖ.УРОВНЯ ",
    "АВАРИЯ ПИТАНИЯ  ",
    "АВАРИЯ ПИТАНИЯ 1",
    "АВАРИЯ ПИТАНИЯ 2",
    "ВОССТ. ПИТАНИЯ  ",
    "ВОССТ. ПИТАНИЯ 1",
    "ВОССТ. ПИТАНИЯ 2",
    "АВАРИЯ БАТАРЕИ  ",
    "АКБ РАЗРЯЖЕНА   ",
    "ОШИБКА ТЕСТА АКБ",
    "ЗАМЕНИТЬ АКБ    ",
    "ВОССТ. БАТАРЕИ  ",
    "РАЗРЯД РЕЗ.БАТ. ",
    "НОРМА РЕЗ.БАТ.  ",
    "АВАРИЯ 220В     ",
    "ВОССТ. 220В     ",
    "ПЕРЕГРУЗКА РИП  ",
    "ТОК В НОРМЕ     ",
    "НЕИСПР. ЗУ РИП  ",
    "ВОССТ. ЗУ РИП   ",
    "ОТКЛЮЧЕН РИП    ",
    "ВКЛЮЧЕН РИП     ",
    "СБРОС ПРИБОРА   ",
    "ПОДМЕНА ПРИБОРА ",
    "ПОТЕРЯН ПРИБОР  ",
    "ОБНАРУЖЕН ПРИБОР",
    "ОТКЛ.ВЕТВИ RS485",
    "ВСТ. ВЕТВИ RS485",
    "КЗ ДПЛС         ",
    "АВАРИЯ ДПЛС     ",
    "ОБРЫВ ДПЛС      ",
    "ВОССТАНОВЛ.ДПЛС ",
    "НЕТ СВЯЗИ ДПЛС1 ",
    "НЕТ СВЯЗИ ДПЛС2 ",
    "УСТ.СВЯЗЬ ДПЛС1 ",
    "УСТ.СВЯЗЬ ДПЛС2 ",
    "ОШИБКА В ОТВЕТЕ ",
    "НЕУСТ. СВЯЗЬ    ",
    "НЕТ КАНАЛА СВЯЗИ",
    "ВСТ.КАНАЛА СВЯЗИ",
    "НЕИЗВ.УСТРОЙСТВО",
    "ОШИБКА ТЕСТА n  ",
    "РАЗДЕЛ ВЗЯТ     ",
    "РАЗДЕЛ СНЯТ     ",
    "ЗАПРОС ВЗЯТИЯ   ",
    "ЗАПРОС СНЯТИЯ   ",
    "ИДЕНТИФИКАЦИЯ ХО",
    "РЕЛЕ ВКЛЮЧЕНО   ",
    "РЕЛЕ ВКЛ.ПРЕРЫВ.",
    "РЕЛЕ ВЫКЛЮЧЕНО  ",
    "ПРОХОД          ",
    "ДОСТУП ОТКЛОНЕН ",
    "ДОСТУП ПРЕДОСТАВ",
    "ДОСТУП ЗАПРЕЩЕН ",
    "ДОСТУП ЗАКРЫТ   ",
    "ДОСТУП ОТКРЫТ   ",
    "ДОСТУП ВОССТАНОВ",
    "ДВЕРЬ ОТКРЫТА   ",
    "ДВЕРЬ ЗАКРЫТА   ",
    "ДВЕРЬ ЗАБЛОКИР. ",
    "ДВЕРЬ ВЗЛОМАНА  ",
    "ПОДБОР КЛЮЧА    ",
    "ПРОГРАММИРОВАНИЕ",
    "ЖУРНАЛ ЗАПОЛНЕН ",
    "ЖУРНАЛ ПЕРЕПОЛН.",
    "ЗАПУСК ТЕСТА    ",
    "ЗВУК ОТКЛЮЧЕН   ",
    "ВКЛЮЧЕНИЕ ПУЛЬТА",
    "ВКЛ. ПРИНТЕРА   ",
    "ВЫКЛ.ПРИНТЕРА   ",
    "ИЗМ. ДАТЫ       ",
    "ИЗМ. ВРЕМЕНИ    ",
    "ДАТА            ",
    "ОТМЕТКА ВРЕМЕНИ ",
    "ОТМЕТКА НАРЯДА  ",]

detector:
  ["ИПР/ип212-45(2)",
   "ПС             ",
   "ИК             ",
   "ШИК            ",
   "КТ             ",
   "ДИП            ",
   "ОС             ",
   "ип-212-45(1)   ",
   "АР-2           ",
   "               ",]